### ISSUE TITLE
Importing grafico model

### ISSUE THREAD

**Issue by stefanluyten** [archi-contribs/archi-json-plugin#9]
Hi

I successfully installed GRAFICO plugin on Mac and PC but experience a strange issue when I try to import a model again.

I export my model (via 'file - export - model as GRAFICO') to a folder 'export' but am unable to import it back into archi.
I select file - import - model from Grafico ... and then nothing happens, no message or error, nothing....

The folder I select is again 'export', and I also tried the subfolder 'model' without success.
I get the same behaviour on both Mac and PC and on Mac I even tried Archi v4 beta ... same issue.

I must be overlooking something silly.

Can someone please help me?

Thanks

Stefan

**Comment by jbsarrodie** [comment]
Hi,

First, if you use the latest version of the plugin, you have to use Archi 4 (still in beta for the moment). Do you confim you use this version ?

Then if nothing happens, this might be because of some issue during import. Can you look at Archi's error file (Help menu > About Archi > Installation details button > Configuration tab > View error log button) ?

Do you have the same issue with the Archissurance model that is provided with Archi ?

If you want, you can also zip your export folder and send it to me so that I can have a look.

Regards,

JB

**Comment by stefanluyten** [comment]
Hi JB

Thanks for your response. I see quite some error in the log, please see below.

I did indeed also try version 4 beta.
This is what I get after re-importing the Archisurance GRAFICO export

!SESSION 2017-02-15 07:33:09.814 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_101
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=nl_BE
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -clean

!ENTRY org.eclipse.ui 4 0 2017-02-15 07:43:48.927
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NoClassDefFoundError: com/archimatetool/model/IRelationship
	at org.archicontribs.grafico.MyImporter.resolveProxies(MyImporter.java:139)
	at org.archicontribs.grafico.MyImporter.doImport(MyImporter.java:81)
	at com.archimatetool.editor.actions.ImportModelAction.run(ImportModelAction.java:40)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1501)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1509)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1313)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4080)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3706)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at com.archimatetool.editor.Application.start(Application.java:87)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
Caused by: java.lang.ClassNotFoundException: com.archimatetool.model.IRelationship cannot be found by org.archicontribs.grafico_0.1.0
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 more


Thanks for the help!

Stefan

**Comment by jbsarrodie** [comment]
Hi,

Can you clarify which version of Grafico you use with which version of Archi. You say you use Archi 4 but from the log you use an old version of Grafico made for Archi 3.x.

Reminder: for Archi 3.x you are stuck with Grafico 0.2, for Archi 4 you have to use Grafico 0.6 (latest).

JB

**Comment by stefanluyten** [comment]
Hi

That was it! I was using an older version of the plugin with Archi 4 beta.
Thanks a lot for helping me out - you pointed me in the right direction!

I installed Grafico 0.6 with Archi 4 and export/import works fine now.

Thanks again and take care
Stefan

**Comment by jbsarrodie** [comment]
Happy to help ;-)

I'm closing this issue.

Regards
